---
title: "Household Survey Processing"
output: html_document
date: "2023-05-16"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(dplyr.summarise.inform = FALSE)
options(scipen = 999)

library(tidyverse)
library(readxl)
```

```{r, include=FALSE}
hh <- read_csv("data/_private/hh_survey/input/AddonHH_OahuV2.csv")
per <- read_csv(
  "data/_private/hh_survey/input/AddonPER_OahuV2.csv",
  col_types = cols(SCHTYP_O = col_character())
)
per_driver <- read_excel("data/_private/hh_survey/input/Oahu_PER_DRIVER.xlsx")
per <- per %>%
  left_join(per_driver, c("HOUSEID", "PERSONID"))
trip <- read_csv("data/_private/hh_survey/input/AddonTRIP_OahuV2.csv")
```

```{r}
translate_table <- function(tbl){
  equiv_tbl <- read_csv("data/_private/hh_survey/input/equiv_table.csv")
  
  variables <- unique(equiv_tbl$VARIABLE)
  col_names <- colnames(tbl)
  for (variable in variables) {
    if (!(variable %in% col_names)) next
    
    tmp <- equiv_tbl %>%
      filter(VARIABLE == variable) %>%
      select(CODE, EQUIV)

    tbl <- tbl %>%
      rename(temp = variable) %>%
      left_join(tmp, by = c("temp" = "CODE")) %>%
      mutate(temp = ifelse(is.na(EQUIV), temp, EQUIV)) %>%
      select(-EQUIV) %>%
      rename(!!variable := temp)
  }
  return(tbl)
}
```

```{r, include=FALSE}
translate_hh <- translate_table(hh)
translate_per <- translate_table(per)
translate_trip <- translate_table(trip)
```

# Checking the survey

```{r}

translate_trip %>%
  group_by(LOOP_TRIP) %>%
  summarize(count = n())

translate_trip %>%
  group_by(TRAVDAY) %>%
  summarize(count = n())

translate_hh %>%
  group_by(FLAG100) %>%
  summarize(count = n())

translate_trip %>%
  group_by(HOUSEID, PERSONID) %>%
  mutate(check = ifelse(ORIGIN_LOCTYPE == "Home", 1, 0)) %>%
  summarize(home_count = sum(check))

```

# Geocoding

```{r, include=FALSE}
hh_pts <- hh %>%
  mutate(unique_id = paste(CONFIRMEDHOME_LONGITUDE, CONFIRMEDHOME_LATITUDE, sep = "_")) %>%
  select(
    unique_id,
    longitude = CONFIRMEDHOME_LONGITUDE,
    latitude = CONFIRMEDHOME_LATITUDE
  )
per_pts <- bind_rows(
  per %>%
    mutate(unique_id = paste(WORKADDRESS_LON, WORKADDRESS_LAT, sep = "_")) %>%
    select(unique_id, longitude = WORKADDRESS_LON, latitude = WORKADDRESS_LAT),
  per %>%
    mutate(unique_id = paste(SCHOOLADDRESS_LON, SCHOOLADDRESS_LAT, sep = "_")) %>%
    select(unique_id, longitude = SCHOOLADDRESS_LON, latitude = SCHOOLADDRESS_LAT)
)
trip_pts <- bind_rows(
  trip %>%
    mutate(unique_id = paste(ORIGIN_LON, ORIGIN_LAT, sep = "_")) %>%
    select(unique_id, longitude = ORIGIN_LON, latitude = ORIGIN_LAT),
  trip %>%
    mutate(unique_id = paste(DESTINATION_LON, DESTINATION_LAT, sep = "_")) %>%
    select(unique_id, longitude = DESTINATION_LON, latitude = DESTINATION_LAT)
)

# Use this table in TransCAD to geocode points to TAZs then read back in
to_geocode <- bind_rows(hh_pts, per_pts, trip_pts) %>%
  group_by(unique_id) %>%
  slice(1)
write_csv(to_geocode, "data/_private/hh_survey/output/to_geocode.csv")
geocoded_pts <- read_csv("data/_private/hh_survey/output/geocoded_points.csv") %>%
  select(unique_id, TAZ)

hh_with_tazs <- translate_hh %>%
  mutate(unique_id = paste(CONFIRMEDHOME_LONGITUDE, CONFIRMEDHOME_LATITUDE, sep = "_")) %>%
  left_join(geocoded_pts, by = "unique_id") %>%
  rename(HomeTAZ = TAZ) %>%
  select(-unique_id)

per_with_taz <- translate_per %>%
  mutate(unique_id = paste(WORKADDRESS_LON, WORKADDRESS_LAT, sep = "_")) %>%
  left_join(geocoded_pts, by = "unique_id") %>%
  rename(WorkTAZ = TAZ) %>%
  mutate(unique_id = paste(SCHOOLADDRESS_LON, SCHOOLADDRESS_LAT, sep = "_")) %>%
  left_join(geocoded_pts, by = "unique_id") %>%
  rename(SchoolTAZ = TAZ) %>%
  select(-unique_id)

trip_with_taz <- translate_trip %>%
  mutate(unique_id = paste(ORIGIN_LON, ORIGIN_LAT, sep = "_")) %>%
  left_join(geocoded_pts, by = "unique_id") %>%
  rename(OriginTAZ = TAZ) %>%
  mutate(unique_id = paste(DESTINATION_LON, DESTINATION_LAT, sep = "_")) %>%
  left_join(geocoded_pts, by = "unique_id") %>%
  rename(DestinationTAZ = TAZ) %>%
  select(-unique_id)
```

# Household Structure

```{r}
# one-hot person variables
per_wrk_stat <- per_with_taz %>%
  mutate(
    WAdult = ifelse(WORKER == "Worker" & R_AGE > 17, 1, 0),
    NWAdult = ifelse(WORKER != "Worker" & R_AGE > 17, 1, 0),
    Kid = ifelse(R_AGE < 18, 1, 0),
    PreSch = ifelse(R_AGE < 6, 1, 0),
    Senior = ifelse(R_AGE > 75, 1, 0),
    WORKER = case_when(
      WORKER == "Worker" & EMPLOYMENT2 >= 32 ~ "FullTime",
      WORKER == "Worker" & EMPLOYMENT2 < 32 ~ "PartTime",
      TRUE ~ WORKER
    )
  )

hhstructure <- per_wrk_stat %>%
  group_by(HOUSEID) %>%
  summarise(
    WAdults = sum(WAdult), NWAdults = sum(NWAdult), HHKids = sum(Kid), 
    HHPreSchs = sum(PreSch), HHSeniors = sum(Senior)
  ) %>%
  mutate(HHStructure = paste0("HH_", WAdults, NWAdults, HHKids))

hh_with_structure <- hh_with_tazs %>%
  left_join(hhstructure, by = "HOUSEID")
```


# Convert to model modes

```{r}
convert_modes <- trip_with_taz %>%
  mutate(
    mode_model = case_when(
      TRPTRANS == "auto" & NUMONTRP == 1 ~ "sov",
      TRPTRANS == "auto" & NUMONTRP == 2 ~ "hov2",
      TRPTRANS == "auto" & NUMONTRP >= 3 ~ "hov3",
      TRUE ~ TRPTRANS
    )
  )
```


# ID Tours

```{r}
# Split 'school' purpose into K12 and Univ based on student status
split_k12_univ <- convert_modes %>%
  left_join(
    per_wrk_stat %>%
      select(HOUSEID, PERSONID, STUDE),
    by = c("HOUSEID", "PERSONID")
  ) %>%
  mutate(
    WHYTO = case_when(
      WHYTO != "School" ~ WHYTO,
      STUDE == "K-12th grade including GED" ~ "K12",
      STUDE == "Full-time college or university" ~ "Univ",
      STUDE == "Part-time college or university" ~ "Univ",
      STUDE == "Vocation/Technical/Trade School" ~ "Univ",
      TRUE ~ "Other"
    )
  )

id_tours <- split_k12_univ %>%
  filter(LOOP_TRIP == "Not a loop trip") %>%
  arrange(HOUSEID, PERSONID, TRIPID) %>%
  group_by(HOUSEID, PERSONID) %>%
  mutate(
    tour_start = case_when(
      TRIPID == 1 ~ 1,
      ORIGIN_LOCTYPE == "Home" ~ 1,
      TRUE ~ 0
    ),
    tour_num = cumsum(tour_start)
  ) %>%
  group_by(HOUSEID, PERSONID, tour_num) %>%
  mutate(
    tour_type = case_when(
      "Work" %in% WHYTO ~ "Work",
      "Univ" %in% WHYTO ~ "Univ",
      "K12" %in% WHYTO ~ "K12",
      "Shopping" %in% WHYTO ~ "Shop",
      TRUE ~ "Other"
    ),
    tour_id = paste(HOUSEID, PERSONID, tour_num, sep = "_")
  )


# Mark tour anchor and intermediate stops
mark_anchor <- id_tours %>%
  mutate(
    temp_dwel = ifelse(DESTINATION_LOCTYPE == "Home", 0, DWELTIME),
    temp_dwel = ifelse(sum(temp_dwel) == 0 & TRIPID == 1, 1, temp_dwel),
    anchor = ifelse(temp_dwel == max(temp_dwel), 100, 0),
    anchor = case_when(
      WHYTO == "Work" ~ anchor + 3,
      WHYTO == "Univ" ~ anchor + 2,
      WHYTO == "K12" ~ anchor + 2,
      TRUE ~ anchor
    ),
    anchor = ifelse(anchor == max(anchor), 1, 0),
    anchor_taz = ifelse(anchor == max(anchor), DestinationTAZ, 0),
    anchor_dwell = ifelse(anchor == max(anchor), DWELTIME, 0),
    check = cumsum(anchor),
    anchor = ifelse(check > 1, 0, anchor),
    int_stop = case_when(
      anchor == 1 ~ 0,
      TRIPID == 1 ~ 0,
      TRIPID == max(TRIPID) ~ 0,
      TRUE ~ 1
    ),
    # check == 0 means the stop is before anchor
    int_stop_fwd = ifelse(check == 0, int_stop, 0),
    int_stop_ret = ifelse(check == 1, int_stop, 0)
  )

id_tour_mode <- mark_anchor %>%
  mutate(
    primary_mode = case_when(
      "rail" %in% mode_model ~ "rail",
      "school_bus" %in% mode_model ~ "school_bus",
      "bus" %in% mode_model ~ "bus",
      "taxi" %in% mode_model ~ "taxi",
      "tnc" %in% mode_model ~ "tnc",
      "trolley" %in% mode_model ~ "trolley",
      "hov3" %in% mode_model ~ "hov3",
      "hov2" %in% mode_model ~ "hov2",
      "sov" %in% mode_model ~ "sov",
      "bike" %in% mode_model ~ "bike",
      "walk" %in% mode_model ~ "walk",
      TRUE ~ "other"
    ),
    temp = ifelse(mode_model == primary_mode, NA, mode_model),
    secondary_mode = case_when(
      "rail" %in% temp ~ "rail",
      "school_bus" %in% temp ~ "school_bus",
      "taxi" %in% temp ~ "taxi",
      "tnc" %in% temp ~ "tnc",
      "trolley" %in% temp ~ "trolley",
      "hov3" %in% temp ~ "hov3",
      "hov2" %in% temp ~ "hov2",
      "sov" %in% temp ~ "sov",
      "bike" %in% temp ~ "bike",
      "walk" %in% temp ~ "walk",
      TRUE ~ ""
    )
  ) %>%
  #
  group_by(HOUSEID, PERSONID, tour_num, mode_model) %>%
  mutate(
    first_bus = ifelse(mode_model == "bus" & TRIPID == min(TRIPID), TRIPID, 0)
  ) %>%
  group_by(HOUSEID, PERSONID, tour_num) %>%
  mutate(
    # nearest_walk = case_when(
    #   primary_mode != "bus" ~ 0,
    #   TRIPID >= max(first_bus) ~ 0,
    #   mode_model != "walk" ~ 0,
    #   TRUE ~ TRIPID
    # ),
    # nearest_drive = case_when(
    #   primary_mode != "bus" ~ 0,
    #   TRIPID >= max(first_bus) ~ 0,
    #   !(mode_model %in% c("sov", "hov2", "hov3")) ~ 0,
    #   TRUE ~ TRIPID
    # )
    access_mode = ifelse(primary_mode == "bus",mode_model[TRIPID == max(first_bus) - 1], ""),
    PSGR_FLG_temp = ifelse(primary_mode == "bus",PSGR_FLG[TRIPID == max(first_bus) - 1], 0),
    access_mode = case_when(
      access_mode == "sov" ~ "pnr",
      access_mode %in% c("hov2", "hov3") & PSGR_FLG_temp == 2 ~ "pnr",
      access_mode %in% c("hov2", "hov3") ~ "knr",
      is.na(access_mode) ~ "walk",
      TRUE ~ access_mode
    )
  ) %>%
  select(-temp, PSGR_FLG_temp)

tour_file <- id_tour_mode %>%
  group_by(tour_id) %>%
  summarize(
    HOUSEID = first(HOUSEID),
    PERSONID = first(PERSONID),
    tour_num = first(tour_num),
    tour_type = first(tour_type),
    tour_num = first(tour_num),
    num_trips = n(),
    anchor_taz = max(anchor_taz),
    anchor_dwell = max(anchor_dwell),
    anchor_time = ENDTIME[anchor == 1],
    int_stop_fwd = sum(int_stop_fwd),
    int_stop_ret = sum(int_stop_ret),
    primary_mode = first(primary_mode),
    access_mode = first(access_mode),
    secondary_mode = first(secondary_mode)
  ) %>%
  # Add household weight
  left_join(
    hh_with_structure %>%
      select(HOUSEID, weight = WTHHFIN5D_HI),
    by = "HOUSEID"
  )
```

```{r}
tours_by_hh <- tour_file %>%
  group_by(HOUSEID, PERSONID, tour_type) %>%
  summarize(count = n()) %>%
  pivot_wider(
    id_cols = c(HOUSEID, PERSONID), names_from = tour_type, 
    values_from = count, values_fill = 0
  ) %>%
  mutate(WorkersThatDay = ifelse(Work > 0, 1, 0)) %>%
  group_by(HOUSEID) %>%
  summarize(across(Other:WorkersThatDay, ~ sum(.x))) %>%
  rename_with(~ paste0(.x, "_tours"), Other:Univ)

hh_add_tours <- hh_with_structure %>%
  left_join(tours_by_hh, by = "HOUSEID") %>%
  mutate(across(Other_tours:WorkersThatDay, ~replace_na(.x, 0))) %>%
  relocate(WorkersThatDay, .after = WAdults) %>%
  mutate(
    BasicPattern = paste0(
      "P_",
      WorkersThatDay,
      NUMADLT - WorkersThatDay, # adults not working that day,
      HHKids
    )
  )
```

## Add tour summary to person file

```{r}
tours_by_per <- tour_file %>%
  group_by(HOUSEID, PERSONID, tour_type) %>%
  summarize(count = n()) %>%
  pivot_wider(
    id_cols = HOUSEID:PERSONID, names_from = tour_type, 
    values_from = count, values_fill = 0
  ) %>%
  rename_with(~ paste0(.x, "_tours"), Other:Univ)

per_add_tour_counts <- per_wrk_stat %>%
  left_join(hh_with_tazs, by = "HOUSEID") %>%
  left_join(tours_by_per, by = c("HOUSEID", "PERSONID")) %>%
  mutate(across(Other_tours:Univ_tours, ~replace_na(.x, 0)))
```

## Calibration Target Creation

```{r}
# Auto ownership
auto_own <- hh_add_tours %>%
  mutate(HHVEHCNT = ifelse(HHVEHCNT > 4, 4, HHVEHCNT)) %>%
  group_by(HHVEHCNT) %>%
  summarize(weight = sum(WTHHFIN5D_HI, na.rm = TRUE)) %>%
  mutate(target_pct = round(weight / sum(weight) * 100, 1)) %>%
  rename(Alternative = HHVEHCNT) %>%
  select(-weight)

# driver's license
drivers <- per_add_tour_counts %>%
  # don't filter bc the choice model is applied to the full pop
  # filter(R_AGE >= 17) %>%
  group_by(DRIVER) %>%
  summarize(weight = sum(WTHHFIN5D_HI, na.rm = TRUE)) %>%
  mutate(target_pct = round(weight / sum(weight) * 100, 1)) %>%
  rename(Alternative = DRIVER) %>%
  select(-weight)

# Daycare status
daycare <- per_add_tour_counts %>%
  filter(R_AGE <= 5 & SCHOOL1 != "unknown") %>%
  group_by(SCHOOL1) %>%
  summarize(weight = sum(WTHHFIN5D_HI, na.rm = TRUE)) %>%
  mutate(target_pct = round(weight / sum(weight) * 100, 1)) %>%
  rename(Alternative = SCHOOL1) %>%
  select(-weight)

# University status
university <- per_add_tour_counts %>%
  filter(R_AGE >= 18 & SCHOOL1 != "unknown") %>%
  group_by(SCHOOL1) %>%
  summarize(weight = sum(WTHHFIN5D_HI, na.rm = TRUE)) %>%
  mutate(target_pct = round(weight / sum(weight) * 100, 1)) %>%
  rename(Alternative = SCHOOL1) %>%
  select(-weight)

# Full/Part time
worker_cat <- per_add_tour_counts %>%
  filter(WORKER %in% c("FullTime", "PartTime")) %>%
  group_by(WORKER) %>%
  summarize(weight = sum(WTHHFIN5D_HI, na.rm = TRUE)) %>%
  mutate(target_pct = round(weight / sum(weight) * 100, 1)) %>%
  rename(Alternative = WORKER) %>%
  select(-weight)

# Remote work %
remote_work <- per_add_tour_counts %>%
  # mutate(remote_worker = ifelse(WKFMHM22 > 1, 1, 0)) %>%
  mutate(remote_worker = case_when(
    WKFMHM22 == 2 ~ 1.5/5, # reported 1-2 days a week
    WKFMHM22 == 3 ~ 3.5/5, # reported 3-4 days a week
    WKFMHM22 == 4 ~ 5/5,   # reported 5 days a week
    TRUE ~ 0
  )) %>%
  group_by(OATYP_JOB1, remote_worker) %>%
  summarize(weight = sum(WTHHFIN5D_HI, na.rm = TRUE)) %>%
  mutate(target_pct = round(weight / sum(weight) * 100, 1)) %>%
  rename(Alternative = OATYP_JOB1) %>%
  filter(remote_worker == 1, Alternative != "skip") %>%
  select(-weight, -remote_worker)

# Days worked per week not provided. Field "EMPLOYMENT2" gives hours
# worked per week, but that can't be translated into days. (e.g. 4 10s vs 5 8s)

# mandatory tour frequency
tour_frequency <- tour_file %>%
  group_by(HOUSEID, PERSONID, tour_type) %>%
  summarize(
    count = n(), 
    weight = sum(weight, na.rm = TRUE)
  ) %>%
  mutate(count = ifelse(count > 2, 2, count)) %>%
  group_by(tour_type, count) %>%
  summarize(weight = sum(weight)) %>%
  mutate(target_pct = round(weight / sum(weight) * 100, 1)) %>%
  select(-weight) %>%
  pivot_wider(names_from = tour_type, values_from = target_pct) %>%
  rename(Alternative = count)

# mandatory tour mode shares
mode_choice <- tour_file %>%
  # # Add worker status
  # left_join(
  #   per_add_tour_counts %>%
  #     select(HOUSEID, PERSONID, WORKER),
  #   by = c("HOUSEID", "PERSONID")
  # ) %>%
  mutate(
    # tour_type = case_when(
    #   tour_type != "Work" ~ tour_type,
    #   WORKER == "FullTime" ~ "Work (FT)",
    #   TRUE ~ "Work (PT)"
    # ),
    primary_mode = ifelse(primary_mode %in% c("hov2", "hov3"), "hov", primary_mode),
    primary_mode = ifelse(
      access_mode != "",
      paste0(access_mode, "_", primary_mode),
      primary_mode
    )
  ) %>%
  group_by(tour_type, primary_mode) %>%
  summarize(weight = sum(weight, na.rm = TRUE)) %>%
  mutate(target_pct = round(weight / sum(weight) * 100, 1)) %>%
  select(-weight) %>%
  pivot_wider(names_from = tour_type, values_from = target_pct) %>%
  # arrange(desc(`Work (FT)`)) %>%
  arrange(desc(Work)) %>%
  # relocate(`Work (FT)`:`Work (PT)`, .after = primary_mode) %>%
  relocate(Other, .after = Univ)

# Mandatory time of day
tod <- tour_file %>%
  # Add worker status
  left_join(
    per_add_tour_counts %>%
      select(HOUSEID, PERSONID, WORKER),
    by = c("HOUSEID", "PERSONID")
  ) %>%
  mutate(
    tour_type = case_when(
      tour_type != "Work" ~ tour_type,
      WORKER == "FullTime" ~ "Work (FT)",
      TRUE ~ "Work (PT)"
    ),
    hour = anchor_time %/% 100
  ) %>%
  group_by(tour_type, hour) %>%
  summarize(weight = sum(weight, na.rm = TRUE)) %>%
  mutate(target_pct = round(weight / sum(weight) * 100, 1)) %>%
  select(-weight) %>%
  pivot_wider(names_from = tour_type, values_from = target_pct) %>%
  arrange(hour) %>%
  rename(Alternative = hour)

# Mandatory activity duration
activity_duration <- tour_file %>%
  # Add worker status
  left_join(
    per_add_tour_counts %>%
      select(HOUSEID, PERSONID, WORKER),
    by = c("HOUSEID", "PERSONID")
  ) %>%
  mutate(
    tour_type = case_when(
      tour_type != "Work" ~ tour_type,
      WORKER == "FullTime" ~ "Work (FT)",
      TRUE ~ "Work (PT)"
    ),
    anchor_dwell = anchor_dwell %/% 60,
    anchor_dwell = ifelse(anchor_dwell > 15, 15, anchor_dwell)
  ) %>%
  filter(anchor_dwell >= 0) %>%
  group_by(tour_type, anchor_dwell) %>%
  summarize(weight = sum(weight, na.rm = TRUE)) %>%
  mutate(target_pct = round(weight / sum(weight) * 100, 2)) %>%
  select(-weight) %>%
  pivot_wider(names_from = tour_type, values_from = target_pct) %>%
  arrange(anchor_dwell) %>%
  rename(Alternative = anchor_dwell)

# Intermediate stop frequency
intermediate_freq <- tour_file %>%
  mutate(
    int_stop_fwd = ifelse(int_stop_fwd > 1, 1, int_stop_fwd),
    int_stop_ret = ifelse(int_stop_ret > 1, 1, int_stop_ret),
    Alternative = paste0(int_stop_fwd, "_", int_stop_ret)
  ) %>%
  group_by(tour_type, Alternative) %>%
  summarize(weight = sum(weight, na.rm = TRUE)) %>%
  mutate(target_pct = round(weight / sum(weight) * 100, 1)) %>%
  select(-weight) %>%
  pivot_wider(names_from = tour_type, values_from = target_pct)

# Intermediate stop duration
int_stop_duration <- id_tour_mode %>%
  filter(int_stop == 1, DWELTIME <= 180) %>%
  mutate(Alternative = case_when(
    DWELTIME <= 15 ~ "0 to 15",
    DWELTIME <= 30 ~ "15 to 30",
    DWELTIME <= 45 ~ "30 to 45",
    DWELTIME <= 60 ~ "45 to 60",
    DWELTIME <= 75 ~ "60 to 75",
    DWELTIME <= 90 ~ "75 to 90",
    DWELTIME <= 105 ~ "90 to 105",
    DWELTIME <= 120 ~ "105 to 120",
    TRUE ~ "120 to 180"
  )) %>%
  # add this just to make sorting the table easier
  mutate(ID = case_when(
    DWELTIME <= 15 ~ 1,
    DWELTIME <= 30 ~ 2,
    DWELTIME <= 45 ~ 3,
    DWELTIME <= 60 ~ 4,
    DWELTIME <= 75 ~ 5,
    DWELTIME <= 90 ~ 6,
    DWELTIME <= 105 ~ 7,
    DWELTIME <= 120 ~ 8,
    TRUE ~ 9
  )) %>%
  group_by(tour_type, Alternative) %>%
  summarize(ID = first(ID), weight = sum(WTTRDFIN5D_HI, na.rm = TRUE)) %>%
  mutate(target_pct = round(weight / sum(weight) * 100, 1)) %>%
  select(-weight) %>%
  pivot_wider(names_from = tour_type, values_from = target_pct) %>%
  arrange(ID) %>%
  select(-ID)
```


```{r, eval=FALSE}
# Outputs
write_csv(per_add_tour_counts, "data/_private/hh_survey/output/output_persons.csv", na = "")
write_csv(hh_add_tours, "data/_private/hh_survey/output/output_households.csv", na = "")
write_csv(tour_file, "data/_private/hh_survey/output/output_tours.csv", na = "")
write_csv(id_tour_mode, "data/_private/hh_survey/output/output_trips.csv", na = "")

# calibration targets
write_csv(auto_own, "data/_private/hh_survey/output/calibration_targets/auto_ownership.csv", na = "")
write_csv(drivers, "data/_private/hh_survey/output/calibration_targets/drivers.csv", na = "")
write_csv(daycare, "data/_private/hh_survey/output/calibration_targets/daycare.csv", na = "")
write_csv(university, "data/_private/hh_survey/output/calibration_targets/university.csv", na = "")
write_csv(worker_cat, "data/_private/hh_survey/output/calibration_targets/worker_cat.csv", na = "")
write_csv(remote_work, "data/_private/hh_survey/output/calibration_targets/remote_work.csv", na = "")
write_csv(remote_work, "data/_private/hh_survey/output/calibration_targets/remote_work.csv", na = "")
write_csv(tour_frequency, "data/_private/hh_survey/output/calibration_targets/tour_frequency.csv", na = "")
write_csv(mode_choice, "data/_private/hh_survey/output/calibration_targets/mode_choice.csv", na = "")
write_csv(tod, "data/_private/hh_survey/output/calibration_targets/time_of_day.csv", na = "")
write_csv(activity_duration, "data/_private/hh_survey/output/calibration_targets/activity_duration.csv", na = "")
write_csv(intermediate_freq, "data/_private/hh_survey/output/calibration_targets/intermediate_freq.csv", na = "")
write_csv(int_stop_duration, "data/_private/hh_survey/output/calibration_targets/int_stop_duration.csv", na = "")
```

